export interface User {
    id?: number,
    name: string,
    email: string,
    password: string,
    phone: string,
    userType: string,
    familyIncome?: number,
    peopleQuantity?: number,
    municipalityId: number,
    hasChildren?: boolean,
    numberOfChildren?: number,
    documents?: string[],
    images?: string[],
    able?: boolean,
}
